allowBuilds:
  sharp: set this to true or false
  unrs-resolver: set this to true or false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - baseline-browser-mapping@2.11.10
  - jose@6.2.7
